client_id = "3d52027991f101f3ede937a1d65dd8d0"
name = "Custom fee value for plus"
application_url = "https://custom-fee-value.vercel.app"
embedded = true

[build]
automatically_update_urls_on_dev = true

[access_scopes]
scopes = "read_products,write_products,write_publications,read_publications,read_cart_transforms,write_cart_transforms"

[auth]
redirect_urls = [
  "https://custom-fee-value.vercel.app/auth/callback"
]

[webhooks]
# ✅ Usa una versión Admin API válida/estable
api_version = "2025-01"

[[webhooks.subscriptions]]
topics = ["app/scopes_update"]
uri = "/webhooks/app/scopes_update"

[[webhooks.subscriptions]]
topics = ["app/uninstalled"]
uri = "/webhooks/app/uninstalled"

# ✅ Mandatory compliance webhooks
[[webhooks.subscriptions]]
compliance_topics = ["customers/data_request", "customers/redact", "shop/redact"]
uri = "/webhooks/compliance"
